=== zwave-js/node-zwave-js/maintenance/schemas/device-config.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"type": "object",
	"properties": {
		"$import": { "$ref": "#/definitions/import" },
		"manufacturer": {
			"$ref": "#/definitions/conditionalString2",
			"description": "The full name of the manufacturer"
		},
		"manufacturerId": {
			"type": "string",
			"description": "The manufacturer ID as assigned by the Z-Wave Alliance",
			"pattern": "^0x[0-9a-f]{4}$"
		},
		"label": {
			"$ref": "#/definitions/conditionalString2",
			"description": "The device label that will be displayed by applications. Should usually be short."
		},
		"description": {
			"$ref": "#/definitions/conditionalString2",
			"description": "A slightly more detailed description of this device, explaining what kind of device this is"
		},
		"devices": {
			"type": "array",
			"description": "An array of product type and product ID combinations",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"productType": {
						"type": "string",
						"description": "The product type of this device as a 4-digit hex string",
						"pattern": "^0x[0-9a-f]{4}$"
					},
					"productId": {
						"type": "string",
						"description": "The product ID of this device as a 4-digit hex string",
						"pattern": "^0x[0-9a-f]{4}$"
					},
					"zwaveAllianceId": {
						"description": "The IDs of the Z-Wave Alliance product database belonging to this device",
						"oneOf": [
							{ "type": "integer" },
							{
								"type": "array",
								"minItems": 1,
								"items": { "type": "integer" },
								"uniqueItems": true
							}
						]
					}
				},
				"required": ["productType", "productId"],
				"additionalProperties": false
			}
		},
		"firmwareVersion": {
			"type": "object",
			"properties": {
				"min": {
					"type": "string",
					"description": "The minimum firmware version this config file targets",
					"pattern": "^[0-9]|[1-9][0-9]|[1-2][0-9][0-9]\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9](\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9])?$"
				},
				"max": {
					"type": "string",
					"description": "The maximum firmware version this config file targets",
					"pattern": "^[0-9]|[1-9][0-9]|[1-2][0-9][0-9]\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9](\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9])?$"
				}
			},
			"required": ["min", "max"],
			"additionalProperties": false
		},
		"preferred": {
			"const": true,
			"description": "Mark this configuration file as preferred over others with overlapping firmware version ranges"
		},
		"supportsZWavePlus": {
			"const": true
		},
		"endpoints": { "$ref": "#/definitions/endpoints" },
		"associations": { "$ref": "#/definitions/associations" },
		"paramInformation": { "$ref": "#/definitions/paramInformation" },
		"proprietary": {
			"type": "object",
			"description": "A dictionary of settings for the proprietary CC. The settings depend on each proprietary CC implementation."
		},
		"compat": {
			"anyOf": [
				{ "$ref": "#/definitions/compatFlags" },
				{
					"type": "array",
					"items": { "$ref": "#/definitions/compatFlags" },
					"minItems": 1,
					"additionalItems": false
				}
			]
		},
		"metadata": {
			"type": "object",
			"properties": {
				"$import": { "$ref": "#/definitions/import" },
				"wakeup": {
					"$ref": "#/definitions/conditionalString",
					"description": "How to wake up the device manually"
				},
				"inclusion": {
					"$ref": "#/definitions/conditionalString",
					"description": "Inclusion instructions for this device"
				},
				"exclusion": {
					"$ref": "#/definitions/conditionalString",
					"description": "Exclusion instructions for this device"
				},
				"reset": {
					"$ref": "#/definitions/conditionalString",
					"description": "Instructions for resetting the device to factory defaults"
				},
				"manual": {
					"$ref": "#/definitions/conditionalString",
					"description": "A link to the device manual"
				},
				"comments": {
					"oneOf": [
						{
							"type": "array",
							"items": {
								"$ref": "#/definitions/comment"
							},
							"minItems": 1
						},
						{
							"$ref": "#/definitions/comment"
						}
					]
				}
			},
			"additionalProperties": false,
			"minProperties": 1
		}
	},
	"anyOf": [
		{
			"required": [
				"manufacturer",
				"manufacturerId",
				"label",
				"description",
				"devices",
				"firmwareVersion"
			]
		},
		{
			"required": ["$import"]
		}
	],
	"additionalProperties": false,
	"definitions": {
		"import": {
			"type": "string",
			"description": "Used to import another config file or parts thereof",
			"pattern": "^((?<dir>((?:~/)?[\\w\\d_\\.-]+/)+)?(?<filename>[\\w\\d_-]+\\.json))?(?<selector>#([\\w\\d\\[\\]_-]+/)*[\\w\\d\\[\\]_-]+)?$"
		},
		"condition": {
			"type": "string",
			"description": "A condition that must be fulfilled for this entry to exit."
		},
		"conditionalString": {
			"anyOf": [
				{ "type": "string" },
				{
					"type": "array",
					"minItems": 1,
					"items": {
						"anyOf": [
							{ "type": "string" },
							{
								"type": "object",
								"properties": {
									"$if": {
										"$ref": "#/definitions/condition"
									},
									"value": {
										"type": "string"
									}
								},
								"required": ["value"],
								"additionalProperties": false
							}
						]
					}
				}
			]
		},
		"conditionalString2": {
			"anyOf": [
				{ "type": "string" },
				{
					"type": "array",
					"minItems": 2,
					"items": {
						"anyOf": [
							{ "type": "string" },
							{
								"type": "object",
								"properties": {
									"$if": {
										"$ref": "#/definitions/condition"
									},
									"value": {
										"type": "string"
									}
								},
								"required": ["value"],
								"additionalProperties": false
							}
						]
					}
				}
			]
		},
		"endpoints": {
			"type": "object",
			"description": "Endpoint-specific configuration",
			"patternProperties": {
				"^\\d+$": {
					"type": "object",
					"properties": {
						"$import": { "$ref": "#/definitions/import" },
						"$if": { "$ref": "#/definitions/condition" },
						"label": {
							"type": "string"
						},
						"associations": {
							"$ref": "#/definitions/associations"
						},
						"paramInformation": {
							"$ref": "#/definitions/paramInformation"
						}
					},
					"additionalProperties": false
				},
				"additionalProperties": false
			}
		},
		"associations": {
			"type": "object",
			"description": "Define association groups for devices that don't support Z-Wave+ or modify the reported associations for devices that do.",
			"properties": {
				"$import": { "$ref": "#/definitions/import" }
			},
			"patternProperties": {
				"^\\d+$": {
					"type": "object",
					"properties": {
						"$import": { "$ref": "#/definitions/import" },
						"$if": { "$ref": "#/definitions/condition" },
						"label": {
							"type": "string",
							"description": "How this association group is called"
						},
						"description": {
							"type": "string",
							"description": "What this association group does"
						},
						"maxNodes": {
							"type": "number",
							"description": "How many nodes may be assigned to this group",
							"minimum": 1
						},
						"isLifeline": {
							"type": "boolean",
							"description": "Whether this is a Lifeline group. SHOULD exist exactly once, some nodes require more groups to report everything."
						},
						"multiChannel": {
							"type": "boolean",
							"description": "`true`: Force a multi channel association (if possible); `false`: Force a node association (if possible)"
						}
					},
					"anyOf": [
						{
							"required": ["label", "maxNodes"]
						},
						{
							"required": ["$import"]
						}
					],
					"additionalProperties": false
				}
			},
			"additionalProperties": false
		},
		"paramInformation": {
			"type": "array",
			"description": "Defines all the existing configuration parameters",
			"items": { "$ref": "#/definitions/param" },
			"minItems": 1,
			"additionalItems": false
		},
		"ccInfo": {
			"type": "object",
			"properties": {
				"isSupported": {
					"type": "boolean"
				},
				"isControlled": {
					"type": "boolean"
				},
				"secure": {
					"type": "boolean"
				},
				"version": {
					"type": "number"
				}
			},
			"additionalProperties": false
		},
		"ccInfoAndEndpoints": {
			"type": "object",
			"properties": {
				"isSupported": {
					"type": "boolean"
				},
				"isControlled": {
					"type": "boolean"
				},
				"secure": {
					"type": "boolean"
				},
				"version": {
					"type": "number"
				},
				"endpoints": {
					"type": "object",
					"patternProperties": {
						"^\\d+$": {
							"$ref": "#/definitions/ccInfo"
						}
					},
					"additionalProperties": false
				}
			},
			"additionalProperties": false
		},
		"param": {
			"type": "object",
			"properties": {
				"#": {
					"type": "string",
					"pattern": "^\\d+(\\[0x[0-9a-f]{1,8}\\])?$"
				},
				"$import": { "$ref": "#/definitions/import" },
				"$if": { "$ref": "#/definitions/condition" },
				"label": {
					"type": "string",
					"description": "A short name for the parameter"
				},
				"description": {
					"type": "string",
					"description": "A longer description what the parameter does"
				},
				"valueSize": {
					"type": "number",
					"minimum": 1,
					"maximum": 4,
					"description": "How many bytes the device uses for this value"
				},
				"minValue": {
					"type": "number",
					"description": "The minimum allowed value for this parameter"
				},
				"maxValue": {
					"type": "number",
					"description": "The maximum allowed value for this parameter"
				},
				"unit": {
					"type": "string",
					"description": "In which unit the value is interpreted"
				},
				"unsigned": {
					"type": "boolean",
					"description": "Whether this parameter is interpreted as an unsigned value by the device (default: false). This simplifies usage for the end user."
				},
				"defaultValue": {
					"type": "number",
					"description": "The factory default value of this parameter."
				},
				"readOnly": {
					"const": true,
					"description": "Whether this parameter can only be read"
				},
				"writeOnly": {
					"const": true,
					"description": "Whether this parameter can only be written"
				},
				"allowManualEntry": {
					"const": false,
					"description": "Whether this parameter accepts any value between minValue and maxValue. If false, minValue and maxValue are optional, but options must be used to specify the allowed values."
				},
				"options": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"$import": {
								"$ref": "#/definitions/import"
							},
							"$if": {
								"$ref": "#/definitions/condition"
							},
							"label": {
								"type": "string",
								"description": "The option label to display"
							},
							"value": {
								"type": "number",
								"description": "Which value this option represents"
							}
						},
						"anyOf": [
							{
								"required": ["label", "value"]
							},
							{
								"required": ["$import"]
							}
						],
						"additionalProperties": false
					}
				}
			},
			"additionalProperties": false,
			"anyOf": [
				{
					"if": {
						"properties": {
							"readOnly": {
								"const": true
							}
						}
					},
					"then": {
						"required": ["#", "label", "valueSize"]
					},
					"else": {
						"required": ["#", "label", "valueSize", "defaultValue"]
					}
				},
				{
					"required": ["#", "$import"]
				}
			]
		},
		"compatFlags": {
			"type": "object",
			"properties": {
				"$if": { "$ref": "#/definitions/condition" },
				"$import": { "$ref": "#/definitions/import" },
				"alarmMapping": {
					"description": "Is used to map legacy V1 alarm values to V2+ Notification events",
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"$import": { "$ref": "#/definitions/import" },
							"from": {
								"type": "object",
								"properties": {
									"alarmType": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									},
									"alarmLevel": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									}
								},
								"additionalProperties": false,
								"required": ["alarmType"]
							},
							"to": {
								"type": "object",
								"properties": {
									"notificationType": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									},
									"notificationEvent": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									},
									"eventParameters": {
										"type": "object",
										"additionalProperties": {
											"anyOf": [
												{
													"type": "integer"
												},
												{
													"enum": ["alarmLevel"]
												}
											]
										}
									}
								},
								"additionalProperties": false,
								"required": [
									"notificationType",
									"notificationEvent"
								]
							}
						},
						"additionalProperties": false,
						"anyOf": [
							{
								"required": ["from", "to"]
							},
							{
								"required": ["$import"]
							}
						]
					},
					"minItems": 1,
					"additionalItems": false
				},
				"commandClasses": {
					"type": "object",
					"properties": {
						"add": {
							"type": "object",
							"additionalProperties": {
								"$ref": "#/definitions/ccInfoAndEndpoints"
							}
						},
						"remove": {
							"type": "object",
							"additionalProperties": {
								"type": "object",
								"properties": {
									"endpoints": {
										"anyOf": [
											{ "const": "*" },
											{
												"type": "array",
												"items": {
													"type": "integer",
													"minimum": 0
												},
												"minItems": 1
											}
										]
									}
								},
								"additionalProperties": false
							}
						}
					},
					"additionalProperties": false
				},
				"disableAutoRefresh": {
					"const": true
				},
				"disableBasicMapping": {
					"const": true
				},
				"disableCallbackFunctionTypeCheck": {
					"type": "array",
					"items": {
						"type": "integer",
						"minimum": 1
					},
					"minItems": 1
				},
				"disableStrictEntryControlDataValidation": {
					"const": true
				},
				"disableStrictMeasurementValidation": {
					"const": true
				},
				"enableBasicSetMapping": {
					"const": true
				},
				"forceNotificationIdleReset": {
					"const": true
				},
				"forceSceneControllerGroupCount": {
					"type": "number",
					"minimum": 0,
					"maximum": 255
				},
				"manualValueRefreshDelayMs": {
					"type": "number",
					"minimum": 0
				},
				"mapRootReportsToEndpoint": {
					"type": "number",
					"minimum": 1
				},
				"overrideFloatEncoding": {
					"type": "object",
					"properties": {
						"size": {
							"type": "integer",
							"minimum": 1,
							"maximum": 4
						},
						"precision": {
							"type": "integer",
							"minimum": 0
						}
					},
					"minProperties": 1,
					"additionalProperties": false
				},
				"overrideQueries": {
					"type": "object",
					"additionalProperties": {
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "object",
							"properties": {
								"endpoint": { "type": "integer", "minimum": 0 },
								"method": { "type": "string" },
								"matchArgs": { "type": "array" },
								"result": true,
								"persistValues": { "type": "object" },
								"extendMetadata": { "type": "object" }
							},
							"required": ["method", "result"],
							"additionalProperties": false
						}
					}
				},
				"preserveEndpoints": {
					"oneOf": [
						{
							"const": "*"
						},
						{
							"type": "array",
							"minItems": 1,
							"items": {
								"type": "integer",
								"minimum": 1
							}
						}
					]
				},
				"preserveRootApplicationCCValueIDs": {
					"const": true
				},
				"queryOnWakeup": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "array",
						"items": [{ "type": "string" }, { "type": "string" }],
						"additionalItems": {
							"anyOf": [
								{ "type": "string" },
								{ "type": "number" },
								{ "type": "boolean" }
							]
						}
					}
				},
				"removeEndpoints": {
					"oneOf": [
						{
							"const": "*"
						},
						{
							"type": "array",
							"minItems": 1,
							"items": {
								"type": "integer",
								"minimum": 1
							}
						}
					]
				},
				"reportTimeout": {
					"type": "number",
					"minimum": 1000,
					"maximum": 10000
				},
				"skipConfigurationNameQuery": {
					"const": true
				},
				"skipConfigurationInfoQuery": {
					"const": true
				},
				"treatBasicSetAsEvent": {
					"const": true
				},
				"treatMultilevelSwitchSetAsEvent": {
					"const": true
				},
				"treatDestinationEndpointAsSource": {
					"const": true
				},
				"useUTCInTimeParametersCC": {
					"const": true
				}
			},
			"additionalProperties": false
		},
		"comment": {
			"type": "object",
			"properties": {
				"$if": {
					"$ref": "#/definitions/condition"
				},
				"$import": { "$ref": "#/definitions/import" },
				"level": {
					"type": "string",
					"enum": ["info", "warning", "error"]
				},
				"text": {
					"type": "string",
					"description": "The actual comment"
				}
			},
			"additionalProperties": false,
			"anyOf": [
				{
					"required": ["level", "text"]
				},
				{
					"required": ["$import"]
				}
			]
		}
	}
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x0077/smoothremote.json
{
	"manufacturer": "INNOVUS",
	"manufacturerId": "0x0077",
	"label": "SmoothRemote",
	"description": "SmoothRemote",
	"devices": [
		{
			"productType": "0x0002",
			"productId": "0x0001"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"associations": {
		"1": {
			"label": "Click I",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"2": {
			"label": "Click II",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"3": {
			"label": "Click III",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"4": {
			"label": "Click IV",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"5": {
			"label": "Click V",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"6": {
			"label": "Click VI",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"7": {
			"label": "Click VII",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"8": {
			"label": "Click VIII",
			"description": "SWITCH ALL ON",
			"maxNodes": 30
		},
		"9": {
			"label": "Click Shift",
			"description": "HAIL",
			"maxNodes": 30
		},
		"10": {
			"label": "Double Click I",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"11": {
			"label": "Double Click II",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"12": {
			"label": "Double Click III",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"13": {
			"label": "Double Click IV",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"14": {
			"label": "Double Click V",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"15": {
			"label": "Double Click VI",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"16": {
			"label": "Double Click VII",
			"description": "BASIC SET",
			"maxNodes": 30
		},
		"17": {
			"label": "Double Click VIII",
			"description": "SWITCH ALL OFF",
			"maxNodes": 30
		},
		"18": {
			"label": "Double Click Shift",
			"description": "HAIL",
			"maxNodes": 30
		},
		"19": {
			"label": "Hold I",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"20": {
			"label": "Hold II",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"21": {
			"label": "Hold III",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"22": {
			"label": "Hold IV",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"23": {
			"label": "Hold V",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"24": {
			"label": "Hold VI",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"25": {
			"label": "Hold VII",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"26": {
			"label": "Hold VIII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"27": {
			"label": "Hold Shift",
			"description": "HAIL",
			"maxNodes": 30
		},
		"28": {
			"label": "Click followed by Hold I",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"29": {
			"label": "Click followed by Hold II",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"30": {
			"label": "Click followed by Hold III",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"31": {
			"label": "Click followed by Hold IV",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"32": {
			"label": "Click followed by Hold V",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"33": {
			"label": "Click followed by Hold VI",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"34": {
			"label": "Click followed by Hold VII",
			"description": "SWITCH MULTILEVEL START LEVEL CHANGE",
			"maxNodes": 30
		},
		"35": {
			"label": "Click followed by Hold VIII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"36": {
			"label": "Click followed by Hold Shift",
			"description": "HAIL",
			"maxNodes": 30
		},
		"37": {
			"label": "Release I",
			"description": "SWITCH MULTILEVEL STOP LEVEL CHANGE",
			"maxNodes": 30
		},
		"38": {
			"label": "Release II",
			"description": "SWITCH MULTILEVEL STOP LEVEL CHANGE",
			"maxNodes": 30
		},
		"39": {
			"label": "Release III",
			"description": "SWITCH MULTILEVEL STOP LEVEL CHANGE",
			"maxNodes": 30
		},
		"40": {
			"label": "Release IV",
			"description": "SWITCH MULTILEVEL STOP LEVEL CHANGE",
			"maxNodes": 30
		},
		"41": {
			"label": "Release V",
			"description": "SWITCH MULTILEVEL STOP LEVEL CHANGE",
			"maxNodes": 30
		},
		"42": {
			"label": "Release VI",
			"description": "SWITCH MULTILEVEL STOP LEVEL CHANGE",
			"maxNodes": 30
		},
		"43": {
			"label": "Release VII",
			"description": "SWITCH MULTILEVEL STOP LEVEL CHANGE",
			"maxNodes": 30
		},
		"44": {
			"label": "Release VIII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"45": {
			"label": "Release Shift",
			"description": "HAIL",
			"maxNodes": 30
		},
		"46": {
			"label": "Click (Shift) followed by Click I",
			"description": "HAIL",
			"maxNodes": 30
		},
		"47": {
			"label": "Click (Shift) followed by Click II",
			"description": "HAIL",
			"maxNodes": 30
		},
		"48": {
			"label": "Click (Shift) followed by Click III",
			"description": "HAIL",
			"maxNodes": 30
		},
		"49": {
			"label": "Click (Shift) followed by Click IV",
			"description": "HAIL",
			"maxNodes": 30
		},
		"50": {
			"label": "Click (Shift) followed by Click V",
			"description": "HAIL",
			"maxNodes": 30
		},
		"51": {
			"label": "Click (Shift) followed by Click VI",
			"description": "HAIL",
			"maxNodes": 30
		},
		"52": {
			"label": "Click (Shift) followed by Click VII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"53": {
			"label": "Click (Shift) followed by Click VIII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"54": {
			"label": "Double Click (Shift) followed by Click I",
			"description": "HAIL",
			"maxNodes": 30
		},
		"55": {
			"label": "Double Click (Shift) followed by Click II",
			"description": "HAIL",
			"maxNodes": 30
		},
		"56": {
			"label": "Double Click (Shift) followed by Click III",
			"description": "HAIL",
			"maxNodes": 30
		},
		"57": {
			"label": "Double Click (Shift) followed by Click IV",
			"description": "HAIL",
			"maxNodes": 30
		},
		"58": {
			"label": "Double Click (Shift) followed by Click V",
			"description": "HAIL",
			"maxNodes": 30
		},
		"59": {
			"label": "Double Click (Shift) followed by Click VI",
			"description": "HAIL",
			"maxNodes": 30
		},
		"60": {
			"label": "Double Click (Shift) followed by Click VII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"61": {
			"label": "Double Click (Shift) followed by Click VIII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"62": {
			"label": "Triple Click VIII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"63": {
			"label": "Triple Click Shift",
			"description": "HAIL",
			"maxNodes": 30
		},
		"64": {
			"label": "4x Click VIII",
			"description": "HAIL",
			"maxNodes": 30
		},
		"65": {
			"label": "4x Click Shift",
			"description": "HAIL",
			"maxNodes": 30
		},
		"66": {
			"label": "Double Click followed by Hold (Shift)",
			"description": "HAIL",
			"maxNodes": 30
		},
		"67": {
			"label": "Triple Click followed by Hold (Shift)",
			"description": "HAIL",
			"maxNodes": 30
		},
		"68": {
			"label": "Triple Click (Shift) followed by Triple Click VIII",
			"description": "HAIL",
			"maxNodes": 30
		}
	},
	"paramInformation": [
		{
			"#": "0",
			"label": "Button Press Time",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 50,
			"unsigned": true
		},
		{
			"#": "1",
			"label": "Button Multiple Press Time",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 100,
			"unsigned": true
		},
		{
			"#": "2",
			"label": "Button Hold Time",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 40,
			"unsigned": true
		},
		{
			"#": "3",
			"label": "Network Update Interval",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 65535,
			"defaultValue": 168,
			"unsigned": true
		}
	]
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x018e/bx-35zw.json
{
	"manufacturer": "Climax Technology, Ltd.",
	"manufacturerId": "0x018e",
	"label": "BX-35ZW",
	"description": "Bellbox",
	"devices": [
		{
			"productType": "0x0002",
			"productId": "0x0011",
			"zwaveAllianceId": 2431
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"paramInformation": [
		{
			"#": "1",
			"label": "Alarm Length",
			"description": "1 minute to 10 minutes",
			"valueSize": 1,
			"unit": "minutes",
			"minValue": 1,
			"maxValue": 10,
			"defaultValue": 10,
			"unsigned": true
		},
		{
			"#": "2",
			"label": "Alarm LED Flash",
			"description": "0:disable, 1: enable",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 1,
			"defaultValue": 1,
			"unsigned": true
		},
		{
			"#": "3",
			"label": "Comfort Led",
			"valueSize": 1,
			"unit": "10 seconds",
			"minValue": 0,
			"maxValue": 250,
			"defaultValue": 0,
			"unsigned": true
		},
		{
			"#": "4",
			"label": "Tamper",
			"description": "0:disable, 1: enable",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 1,
			"defaultValue": 1,
			"unsigned": true
		}
	],
	"metadata": {
		"inclusion": "This product can be included and operated in any Z-Wave network with other Z-Wave certified devices from other manufactures and/or other applications. All non-battery operated nodes within the network will act as repeaters regardless of vendor to increase reliability of the network.\n -Insert the two 1.5V D-Cell alkaline batteries into the battery \n compartment connecting the correct polarity as shown on the \n battery compartment lid.The Bellbox will emit a 2-tone beep.\n -Put the Z-Wave gateway or control panel into Inclusion mode (please \n refer to the Z-Wave gateway or control panel manual).\n -Within 1.5 seconds, press the Function Button 3 times.\n -Refer to the operation manual of the Z-Wave Gateway or Control \n Panel to complete the adding process.\n -If the sensor has already been added (included) into another Z-Wave \n Gateway/Control Panel, or if the sensor is unable to be added into the \n current Z-Wave Gateway/Control Panel, please exclude it first (see \n Removing Device) before attempting to include it into the current Z-\n Wave Gateway/Control Panel.",
		"exclusion": "The Bellbox must be removed from existing Z-Wave network before being included into another. There are two methods available to exclude a device.\n -Put the Z-Wave gateway or control panel into Exclusion mode (please \n refer to the Z-Wave gateway or control panel manual).\n -Within 1.5 seconds, press the Function Button 3 times and the Bellbox \n will be removed from the Z-Wave network.",
		"reset": "(Only use factory reset when network Control Panel/Gateway is missing or inoperable).\n -Press and hold the Function button of the Bellbox for 10 seconds to \n factory reset with all LED flashes once.\n<NOTE>\n -Factory resetting the Bellbox will restore it to factory default \n settings (excluded from the Z-Wave network). The Z-Wave gateway or \n control panel will still keep its Z-Wave settings. Please refer to the \n gateway or control panel manual on how to remove the Bellboxâ€™s Z-\n Wave settings.",
		"manual": "https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/2431/BX-35-ZW_20170508.pdf"
	}
}
