=== zwave-js/node-zwave-js/maintenance/schemas/device-config.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"type": "object",
	"properties": {
		"$import": { "$ref": "#/definitions/import" },
		"manufacturer": {
			"$ref": "#/definitions/conditionalString2",
			"description": "The full name of the manufacturer"
		},
		"manufacturerId": {
			"type": "string",
			"description": "The manufacturer ID as assigned by the Z-Wave Alliance",
			"pattern": "^0x[0-9a-f]{4}$"
		},
		"label": {
			"$ref": "#/definitions/conditionalString2",
			"description": "The device label that will be displayed by applications. Should usually be short."
		},
		"description": {
			"$ref": "#/definitions/conditionalString2",
			"description": "A slightly more detailed description of this device, explaining what kind of device this is"
		},
		"devices": {
			"type": "array",
			"description": "An array of product type and product ID combinations",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"productType": {
						"type": "string",
						"description": "The product type of this device as a 4-digit hex string",
						"pattern": "^0x[0-9a-f]{4}$"
					},
					"productId": {
						"type": "string",
						"description": "The product ID of this device as a 4-digit hex string",
						"pattern": "^0x[0-9a-f]{4}$"
					},
					"zwaveAllianceId": {
						"description": "The IDs of the Z-Wave Alliance product database belonging to this device",
						"oneOf": [
							{ "type": "integer" },
							{
								"type": "array",
								"minItems": 1,
								"items": { "type": "integer" },
								"uniqueItems": true
							}
						]
					}
				},
				"required": ["productType", "productId"],
				"additionalProperties": false
			}
		},
		"firmwareVersion": {
			"type": "object",
			"properties": {
				"min": {
					"type": "string",
					"description": "The minimum firmware version this config file targets",
					"pattern": "^[0-9]|[1-9][0-9]|[1-2][0-9][0-9]\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9](\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9])?$"
				},
				"max": {
					"type": "string",
					"description": "The maximum firmware version this config file targets",
					"pattern": "^[0-9]|[1-9][0-9]|[1-2][0-9][0-9]\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9](\\.[0-9]|[1-9][0-9]|[1-2][0-9][0-9])?$"
				}
			},
			"required": ["min", "max"],
			"additionalProperties": false
		},
		"preferred": {
			"const": true,
			"description": "Mark this configuration file as preferred over others with overlapping firmware version ranges"
		},
		"supportsZWavePlus": {
			"const": true
		},
		"endpoints": { "$ref": "#/definitions/endpoints" },
		"associations": { "$ref": "#/definitions/associations" },
		"paramInformation": { "$ref": "#/definitions/paramInformation" },
		"proprietary": {
			"type": "object",
			"description": "A dictionary of settings for the proprietary CC. The settings depend on each proprietary CC implementation."
		},
		"compat": {
			"anyOf": [
				{ "$ref": "#/definitions/compatFlags" },
				{
					"type": "array",
					"items": { "$ref": "#/definitions/compatFlags" },
					"minItems": 1,
					"additionalItems": false
				}
			]
		},
		"metadata": {
			"type": "object",
			"properties": {
				"$import": { "$ref": "#/definitions/import" },
				"wakeup": {
					"$ref": "#/definitions/conditionalString",
					"description": "How to wake up the device manually"
				},
				"inclusion": {
					"$ref": "#/definitions/conditionalString",
					"description": "Inclusion instructions for this device"
				},
				"exclusion": {
					"$ref": "#/definitions/conditionalString",
					"description": "Exclusion instructions for this device"
				},
				"reset": {
					"$ref": "#/definitions/conditionalString",
					"description": "Instructions for resetting the device to factory defaults"
				},
				"manual": {
					"$ref": "#/definitions/conditionalString",
					"description": "A link to the device manual"
				},
				"comments": {
					"oneOf": [
						{
							"type": "array",
							"items": {
								"$ref": "#/definitions/comment"
							},
							"minItems": 1
						},
						{
							"$ref": "#/definitions/comment"
						}
					]
				}
			},
			"additionalProperties": false,
			"minProperties": 1
		}
	},
	"anyOf": [
		{
			"required": [
				"manufacturer",
				"manufacturerId",
				"label",
				"description",
				"devices",
				"firmwareVersion"
			]
		},
		{
			"required": ["$import"]
		}
	],
	"additionalProperties": false,
	"definitions": {
		"import": {
			"type": "string",
			"description": "Used to import another config file or parts thereof",
			"pattern": "^((?<dir>((?:~/)?[\\w\\d_\\.-]+/)+)?(?<filename>[\\w\\d_-]+\\.json))?(?<selector>#([\\w\\d\\[\\]_-]+/)*[\\w\\d\\[\\]_-]+)?$"
		},
		"condition": {
			"type": "string",
			"description": "A condition that must be fulfilled for this entry to exit."
		},
		"conditionalString": {
			"anyOf": [
				{ "type": "string" },
				{
					"type": "array",
					"minItems": 1,
					"items": {
						"anyOf": [
							{ "type": "string" },
							{
								"type": "object",
								"properties": {
									"$if": {
										"$ref": "#/definitions/condition"
									},
									"value": {
										"type": "string"
									}
								},
								"required": ["value"],
								"additionalProperties": false
							}
						]
					}
				}
			]
		},
		"conditionalString2": {
			"anyOf": [
				{ "type": "string" },
				{
					"type": "array",
					"minItems": 2,
					"items": {
						"anyOf": [
							{ "type": "string" },
							{
								"type": "object",
								"properties": {
									"$if": {
										"$ref": "#/definitions/condition"
									},
									"value": {
										"type": "string"
									}
								},
								"required": ["value"],
								"additionalProperties": false
							}
						]
					}
				}
			]
		},
		"endpoints": {
			"type": "object",
			"description": "Endpoint-specific configuration",
			"patternProperties": {
				"^\\d+$": {
					"type": "object",
					"properties": {
						"$import": { "$ref": "#/definitions/import" },
						"$if": { "$ref": "#/definitions/condition" },
						"label": {
							"type": "string"
						},
						"associations": {
							"$ref": "#/definitions/associations"
						},
						"paramInformation": {
							"$ref": "#/definitions/paramInformation"
						}
					},
					"additionalProperties": false
				},
				"additionalProperties": false
			}
		},
		"associations": {
			"type": "object",
			"description": "Define association groups for devices that don't support Z-Wave+ or modify the reported associations for devices that do.",
			"properties": {
				"$import": { "$ref": "#/definitions/import" }
			},
			"patternProperties": {
				"^\\d+$": {
					"type": "object",
					"properties": {
						"$import": { "$ref": "#/definitions/import" },
						"$if": { "$ref": "#/definitions/condition" },
						"label": {
							"type": "string",
							"description": "How this association group is called"
						},
						"description": {
							"type": "string",
							"description": "What this association group does"
						},
						"maxNodes": {
							"type": "number",
							"description": "How many nodes may be assigned to this group",
							"minimum": 1
						},
						"isLifeline": {
							"type": "boolean",
							"description": "Whether this is a Lifeline group. SHOULD exist exactly once, some nodes require more groups to report everything."
						},
						"multiChannel": {
							"type": "boolean",
							"description": "`true`: Force a multi channel association (if possible); `false`: Force a node association (if possible)"
						}
					},
					"anyOf": [
						{
							"required": ["label", "maxNodes"]
						},
						{
							"required": ["$import"]
						}
					],
					"additionalProperties": false
				}
			},
			"additionalProperties": false
		},
		"paramInformation": {
			"type": "array",
			"description": "Defines all the existing configuration parameters",
			"items": { "$ref": "#/definitions/param" },
			"minItems": 1,
			"additionalItems": false
		},
		"ccInfo": {
			"type": "object",
			"properties": {
				"isSupported": {
					"type": "boolean"
				},
				"isControlled": {
					"type": "boolean"
				},
				"secure": {
					"type": "boolean"
				},
				"version": {
					"type": "number"
				}
			},
			"additionalProperties": false
		},
		"ccInfoAndEndpoints": {
			"type": "object",
			"properties": {
				"isSupported": {
					"type": "boolean"
				},
				"isControlled": {
					"type": "boolean"
				},
				"secure": {
					"type": "boolean"
				},
				"version": {
					"type": "number"
				},
				"endpoints": {
					"type": "object",
					"patternProperties": {
						"^\\d+$": {
							"$ref": "#/definitions/ccInfo"
						}
					},
					"additionalProperties": false
				}
			},
			"additionalProperties": false
		},
		"param": {
			"type": "object",
			"properties": {
				"#": {
					"type": "string",
					"pattern": "^\\d+(\\[0x[0-9a-f]{1,8}\\])?$"
				},
				"$import": { "$ref": "#/definitions/import" },
				"$if": { "$ref": "#/definitions/condition" },
				"label": {
					"type": "string",
					"description": "A short name for the parameter"
				},
				"description": {
					"type": "string",
					"description": "A longer description what the parameter does"
				},
				"valueSize": {
					"type": "number",
					"minimum": 1,
					"maximum": 4,
					"description": "How many bytes the device uses for this value"
				},
				"minValue": {
					"type": "number",
					"description": "The minimum allowed value for this parameter"
				},
				"maxValue": {
					"type": "number",
					"description": "The maximum allowed value for this parameter"
				},
				"unit": {
					"type": "string",
					"description": "In which unit the value is interpreted"
				},
				"unsigned": {
					"type": "boolean",
					"description": "Whether this parameter is interpreted as an unsigned value by the device (default: false). This simplifies usage for the end user."
				},
				"defaultValue": {
					"type": "number",
					"description": "The factory default value of this parameter."
				},
				"readOnly": {
					"const": true,
					"description": "Whether this parameter can only be read"
				},
				"writeOnly": {
					"const": true,
					"description": "Whether this parameter can only be written"
				},
				"allowManualEntry": {
					"const": false,
					"description": "Whether this parameter accepts any value between minValue and maxValue. If false, minValue and maxValue are optional, but options must be used to specify the allowed values."
				},
				"options": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"$import": {
								"$ref": "#/definitions/import"
							},
							"$if": {
								"$ref": "#/definitions/condition"
							},
							"label": {
								"type": "string",
								"description": "The option label to display"
							},
							"value": {
								"type": "number",
								"description": "Which value this option represents"
							}
						},
						"anyOf": [
							{
								"required": ["label", "value"]
							},
							{
								"required": ["$import"]
							}
						],
						"additionalProperties": false
					}
				}
			},
			"additionalProperties": false,
			"anyOf": [
				{
					"if": {
						"properties": {
							"readOnly": {
								"const": true
							}
						}
					},
					"then": {
						"required": ["#", "label", "valueSize"]
					},
					"else": {
						"required": ["#", "label", "valueSize", "defaultValue"]
					}
				},
				{
					"required": ["#", "$import"]
				}
			]
		},
		"compatFlags": {
			"type": "object",
			"properties": {
				"$if": { "$ref": "#/definitions/condition" },
				"$import": { "$ref": "#/definitions/import" },
				"alarmMapping": {
					"description": "Is used to map legacy V1 alarm values to V2+ Notification events",
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"$import": { "$ref": "#/definitions/import" },
							"from": {
								"type": "object",
								"properties": {
									"alarmType": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									},
									"alarmLevel": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									}
								},
								"additionalProperties": false,
								"required": ["alarmType"]
							},
							"to": {
								"type": "object",
								"properties": {
									"notificationType": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									},
									"notificationEvent": {
										"type": "integer",
										"minimum": 0,
										"maximum": 255
									},
									"eventParameters": {
										"type": "object",
										"additionalProperties": {
											"anyOf": [
												{
													"type": "integer"
												},
												{
													"enum": ["alarmLevel"]
												}
											]
										}
									}
								},
								"additionalProperties": false,
								"required": [
									"notificationType",
									"notificationEvent"
								]
							}
						},
						"additionalProperties": false,
						"anyOf": [
							{
								"required": ["from", "to"]
							},
							{
								"required": ["$import"]
							}
						]
					},
					"minItems": 1,
					"additionalItems": false
				},
				"commandClasses": {
					"type": "object",
					"properties": {
						"add": {
							"type": "object",
							"additionalProperties": {
								"$ref": "#/definitions/ccInfoAndEndpoints"
							}
						},
						"remove": {
							"type": "object",
							"additionalProperties": {
								"type": "object",
								"properties": {
									"endpoints": {
										"anyOf": [
											{ "const": "*" },
											{
												"type": "array",
												"items": {
													"type": "integer",
													"minimum": 0
												},
												"minItems": 1
											}
										]
									}
								},
								"additionalProperties": false
							}
						}
					},
					"additionalProperties": false
				},
				"disableAutoRefresh": {
					"const": true
				},
				"disableBasicMapping": {
					"const": true
				},
				"disableCallbackFunctionTypeCheck": {
					"type": "array",
					"items": {
						"type": "integer",
						"minimum": 1
					},
					"minItems": 1
				},
				"disableStrictEntryControlDataValidation": {
					"const": true
				},
				"disableStrictMeasurementValidation": {
					"const": true
				},
				"enableBasicSetMapping": {
					"const": true
				},
				"forceNotificationIdleReset": {
					"const": true
				},
				"forceSceneControllerGroupCount": {
					"type": "number",
					"minimum": 0,
					"maximum": 255
				},
				"manualValueRefreshDelayMs": {
					"type": "number",
					"minimum": 0
				},
				"mapRootReportsToEndpoint": {
					"type": "number",
					"minimum": 1
				},
				"overrideFloatEncoding": {
					"type": "object",
					"properties": {
						"size": {
							"type": "integer",
							"minimum": 1,
							"maximum": 4
						},
						"precision": {
							"type": "integer",
							"minimum": 0
						}
					},
					"minProperties": 1,
					"additionalProperties": false
				},
				"overrideQueries": {
					"type": "object",
					"additionalProperties": {
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "object",
							"properties": {
								"endpoint": { "type": "integer", "minimum": 0 },
								"method": { "type": "string" },
								"matchArgs": { "type": "array" },
								"result": true,
								"persistValues": { "type": "object" },
								"extendMetadata": { "type": "object" }
							},
							"required": ["method", "result"],
							"additionalProperties": false
						}
					}
				},
				"preserveEndpoints": {
					"oneOf": [
						{
							"const": "*"
						},
						{
							"type": "array",
							"minItems": 1,
							"items": {
								"type": "integer",
								"minimum": 1
							}
						}
					]
				},
				"preserveRootApplicationCCValueIDs": {
					"const": true
				},
				"queryOnWakeup": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "array",
						"items": [{ "type": "string" }, { "type": "string" }],
						"additionalItems": {
							"anyOf": [
								{ "type": "string" },
								{ "type": "number" },
								{ "type": "boolean" }
							]
						}
					}
				},
				"removeEndpoints": {
					"oneOf": [
						{
							"const": "*"
						},
						{
							"type": "array",
							"minItems": 1,
							"items": {
								"type": "integer",
								"minimum": 1
							}
						}
					]
				},
				"reportTimeout": {
					"type": "number",
					"minimum": 1000,
					"maximum": 10000
				},
				"skipConfigurationNameQuery": {
					"const": true
				},
				"skipConfigurationInfoQuery": {
					"const": true
				},
				"treatBasicSetAsEvent": {
					"const": true
				},
				"treatMultilevelSwitchSetAsEvent": {
					"const": true
				},
				"treatDestinationEndpointAsSource": {
					"const": true
				},
				"useUTCInTimeParametersCC": {
					"const": true
				}
			},
			"additionalProperties": false
		},
		"comment": {
			"type": "object",
			"properties": {
				"$if": {
					"$ref": "#/definitions/condition"
				},
				"$import": { "$ref": "#/definitions/import" },
				"level": {
					"type": "string",
					"enum": ["info", "warning", "error"]
				},
				"text": {
					"type": "string",
					"description": "The actual comment"
				}
			},
			"additionalProperties": false,
			"anyOf": [
				{
					"required": ["level", "text"]
				},
				{
					"required": ["$import"]
				}
			]
		}
	}
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x014a/dwzwave25.json
{
	"manufacturer": "Ecolink",
	"manufacturerId": "0x014a",
	"label": "DWZWAVE25",
	"description": "Z-Wave Door/Window Sensor",
	"devices": [
		{
			"productType": "0x0004",
			"productId": "0x0002"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"paramInformation": [
		{
			"#": "1",
			"label": "Send Basic Set",
			"description": "Send Basic Set to Association Group 2",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 0,
			"unsigned": true,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Don't Send Basic Set",
					"value": 0
				},
				{
					"label": "Send Basic Set",
					"value": 255
				}
			]
		},
		{
			"#": "2",
			"label": "Send Sensor Binary Report",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 0,
			"unsigned": true,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Send Sensor Binary Report",
					"value": 0
				},
				{
					"label": "Don't Send Binary Sensor Report",
					"value": 255
				}
			]
		}
	],
	"compat": {
		"forceNotificationIdleReset": true
	}
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x027a/zse40.json
{
	"manufacturer": "Zooz",
	"manufacturerId": "0x027a",
	"label": "ZSE40",
	"description": "4-in-1 Sensor",
	"devices": [
		{
			"productType": "0x2021",
			"productId": "0x2101"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"paramInformation": [
		{
			"#": "1",
			"label": "Temperature Scale",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 1,
			"defaultValue": 1,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Celsius",
					"value": 0
				},
				{
					"label": "Fahrenheit",
					"value": 1
				}
			]
		},
		{
			"#": "2",
			"label": "Temperature Reporting Threshold",
			"unit": "0.1 Â°",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 50,
			"defaultValue": 10
		},
		{
			"#": "3",
			"label": "Humidity Reporting Threshold",
			"unit": "%",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 50,
			"defaultValue": 10
		},
		{
			"#": "4",
			"label": "Brightness Reporting Threshold",
			"unit": "%",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 50,
			"defaultValue": 10
		},
		{
			"#": "5",
			"$if": "firmwareVersion < 17.9",
			"label": "Trigger Interval",
			"description": "Set the trigger interval for motion sensor re-activation.",
			"unit": "minutes",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 255,
			"defaultValue": 3,
			"unsigned": true
		},
		{
			"#": "5",
			"$if": "firmwareVersion >= 17.9 && firmwareVersion < 24.2",
			"label": "Trigger Interval",
			"description": "Set the trigger interval for motion sensor re-activation.",
			"unit": "seconds",
			"valueSize": 1,
			"minValue": 15,
			"maxValue": 60,
			"defaultValue": 15,
			"unsigned": true
		},
		{
			"#": "5",
			"$if": "firmwareVersion >= 24.2",
			"label": "Trigger Interval",
			"description": "Set the trigger interval for motion sensor re-activation.",
			"unit": "seconds",
			"valueSize": 1,
			"minValue": 15,
			"maxValue": 255,
			"defaultValue": 15,
			"unsigned": true
		},
		{
			"#": "6",
			"label": "Motion Sensor Sensitivity",
			"description": "Adjust sensitivity of the motion sensor.",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 7,
			"defaultValue": 3,
			"allowManualEntry": false,
			"options": [
				{
					"label": "highest",
					"value": 1
				},
				{
					"label": "higher",
					"value": 2
				},
				{
					"label": "high",
					"value": 3
				},
				{
					"label": "normal",
					"value": 4
				},
				{
					"label": "low",
					"value": 5
				},
				{
					"label": "lower",
					"value": 6
				},
				{
					"label": "lowest",
					"value": 7
				}
			]
		},
		{
			"#": "7",
			"label": "LED indicator mode",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 4,
			"defaultValue": 4,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Off",
					"value": 1
				},
				{
					"label": "Pulsing Temperature, Flashing Motion",
					"value": 2
				},
				{
					"label": "Flashing Temperature and Motion",
					"value": 3
				},
				{
					"label": "No Temperature, Flashing Motion",
					"value": 4
				}
			]
		}
	]
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x0312/zw15.json
{
	"manufacturer": "EVA Logik",
	"manufacturerId": "0x0312",
	"label": "ZW15",
	"description": "Siren Box",
	"devices": [
		{
			"productType": "0x4000",
			"productId": "0x0f1c",
			"zwaveAllianceId": 3383
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"metadata": {
		"inclusion": "1. Follow the instructions for your Z-Wave certified controller to include a device to \n the Z-Wave network.\n2. Once the controller is ready to include your device, triple click the ADD \n Button to include it in the network.\n3. Once your controller has confirmed that the device has been included, refresh the \n Z-Wave network to optimize performance.\n4. The device is associated in the same group when it included in setting process. \n Now you can control your Z-Wave device according to groups, scenes, schedules \n and automation programmed.",
		"exclusion": "1. Follow the instructions for your Z-Wave certified controller to exclude a device \n from the Z-Wave network.\n2. Once the controller is ready to Exclude your device, triple click the ADD Button \n to exclude it from the network.",
		"reset": "1. Press and hold ADD Button for at least 3 seconds while you insert batteries.\n2. Use this procedure only in the event that the network primary controller is missing \n or otherwise inoperable.",
		"manual": "https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/3383/ZW15-Manual190517.pdf"
	}
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x0149/ums2.json
{
	"manufacturer": "wiDom",
	"manufacturerId": "0x0149",
	"label": "UMS2",
	"description": "WiDom Smart Roller Shutter",
	"devices": [
		{
			"productType": "0x1214",
			"productId": "0x0800"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"paramInformation": [
		{
			"#": "1",
			"label": "Numbers of Clicks to Control the Local Load",
			"valueSize": 1,
			"defaultValue": 3,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Disabled",
					"value": 0
				},
				{
					"label": "1 click",
					"value": 1
				},
				{
					"label": "2 clicks",
					"value": 2
				},
				{
					"label": "1 clicks and 2 clicks",
					"value": 3
				}
			]
		},
		{
			"#": "2",
			"label": "Favorite Level for ON Position",
			"valueSize": 1,
			"minValue": 50,
			"maxValue": 100,
			"defaultValue": 100
		},
		{
			"#": "3",
			"label": "Favorite Level for OFF Position",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 49,
			"defaultValue": 0
		},
		{
			"#": "4",
			"label": "Value for Group 2 with 1 Click on UP Button",
			"description": "Allowable range: 0-99, 255",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 255,
			"unsigned": true
		},
		{
			"#": "5",
			"label": "Value for Group 2 with 1 Click on DOWN Button",
			"description": "Allowable range: 0-99, 255",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 0,
			"unsigned": true
		},
		{
			"#": "6",
			"label": "Value for Group 3 with 2 Clicks on UP Button",
			"description": "Allowable range: 0-99, 255",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 255,
			"unsigned": true
		},
		{
			"#": "7",
			"label": "Value for Group 3 with 2 Clicks on DOWN Button",
			"description": "Allowable range: 0-99, 255",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 0,
			"unsigned": true
		},
		{
			"#": "8",
			"label": "Value for Group 4 with 3 Clicks on UP Button",
			"description": "Allowable range: 0-99, 255",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 255,
			"unsigned": true
		},
		{
			"#": "9",
			"label": "Value for Group 4 with 3 Clicks on DOWN Button",
			"description": "Allowable range: 0-99, 255",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 0,
			"unsigned": true
		},
		{
			"#": "20",
			"label": "Calibration",
			"description": "Defines the status of the calibration procedure",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 2,
			"defaultValue": 0
		},
		{
			"#": "21",
			"label": "Motor Idle State Definition",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3000,
			"defaultValue": 1000
		},
		{
			"#": "22",
			"label": "Limit Switch Recognition",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 127,
			"defaultValue": 30
		}
	]
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x0109/zl7432.json
{
	"manufacturer": "Vision Security",
	"manufacturerId": "0x0109",
	"label": "ZL7432",
	"description": "In Wall Dual Relay Switch",
	"devices": [
		{
			"productType": "0x2017",
			"productId": "0x1711",
			"zwaveAllianceId": 859
		},
		{
			"productType": "0x2017",
			"productId": "0x1717",
			"zwaveAllianceId": 1807
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"associations": {
		"1": {
			"label": "Update Controller",
			"maxNodes": 5,
			"isLifeline": true
		}
	},
	"compat": {
		"preserveRootApplicationCCValueIDs": true
	}
}

=== zwave-js/node-zwave-js/packages/config/config/devices/0x027a/zen05.json
{
	"manufacturer": "Zooz",
	"manufacturerId": "0x027a",
	"label": "ZEN05",
	"description": "Outdoor Smart Plug",
	"devices": [
		{
			"productType": "0x7000",
			"productId": "0xb001"
		}
	],
	"firmwareVersion": {
		"min": "1.1",
		"max": "255.255"
	},
	"paramInformation": [
		{
			"#": "1",
			"label": "LED Indicator Mode",
			"valueSize": 1,
			"defaultValue": 0,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Always On",
					"value": 0
				},
				{
					"label": "Follow Outlet",
					"value": 1
				},
				{
					"label": "Always Off",
					"value": 2
				}
			]
		},
		{
			"#": "2",
			"$import": "templates/zooz_template.json#auto_off_timer_duration",
			"label": "Auto Turn-Off Timer Duration "
		},
		{
			"#": "4",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Auto Turn-On Timer"
		},
		{
			"#": "6",
			"$import": "~/templates/master_template.json#state_after_power_failure_prev_on_off"
		},
		{
			"#": "7",
			"label": "Set the brightness level of the LED indicator",
			"valueSize": 1,
			"defaultValue": 2,
			"allowManualEntry": false,
			"options": [
				{
					"label": "high",
					"value": 0
				},
				{
					"label": "medium",
					"value": 1
				},
				{
					"label": "low",
					"value": 2
				}
			]
		},
		{
			"#": "8",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Manual Control",
			"defaultValue": 1
		}
	],
	"compat": {
		"preserveRootApplicationCCValueIDs": true
	}
}
